/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_sachs_easypaint_EasyPaintLib */

#ifndef _Included_me_sachs_easypaint_EasyPaintLib
#define _Included_me_sachs_easypaint_EasyPaintLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_init_window
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1init_1window
  (JNIEnv *, jclass);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_init_render_context
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1init_1render_1context
  (JNIEnv *, jclass);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_load_resource
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1load_1resource
  (JNIEnv *, jclass, jstring);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_on_update
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1on_1update
  (JNIEnv *, jclass, jdouble);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_on_render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1on_1render
  (JNIEnv *, jclass);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_on_resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1on_1resize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_input_manager_touch_down
 * Signature: (I[I[I)V
 */
JNIEXPORT void JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1input_1manager_1touch_1down
  (JNIEnv *, jclass, jint, jintArray, jintArray);

/*
 * Class:     me_sachs_easypaint_EasyPaintLib
 * Method:    app_input_manager_touch_up
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_me_sachs_easypaint_EasyPaintLib_app_1input_1manager_1touch_1up
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
